### ISSUE TITLE
Licensing Terms

### ISSUE THREAD

**Issue by maximecb** [MartinThoma/HASY#16]
Hi there. I'm in the process of creating a simple [3D simulator](https://github.com/maximecb/gym-miniworld) for reinforcement learning tasks, and I would like to include some text in various 3D scenes.

I'm wondering what are the licensing terms of the HASYv2 dataset, wrt redistributing the data. Could I bundle some of this dataset with my simulator, which is MIT licensed?

Kindest regards,

- Maxime

**Comment by MartinThoma** [comment]
Hi Maxime,

thank you for asking. HASYv2 is licensed under ODBL 1.0. I think the best way to use it in free software is to include a reference for HASYv2 within the project, e.g.:

> This project uses the HASYv2 dataset:
> Thoma, Martin. "The HASYv2 dataset." arXiv preprint arXiv:1701.08380 (2017).
> https://arxiv.org/abs/1701.08380

Depending on how important this dataset is for your project, I would expect it to have a similar representation / visibility. So if it is only a minor part as you make it sound - rather a decoration then actual content - then it's fine to include it in a less visible file, e.g. something like `gym-miniworld/docs/datasets.md` or `gym-miniworld/docs/third-party-content.md`.

**Comment by maximecb** [comment]
Ok thank you.
